plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - animation/01-button-hover/README.md
  - animation/02-pop-up/README.md
  - flex/01-flex-center/README.md
  - flex/02-flex-header/README.md
  - flex/03-flex-header-2/README.md
  - flex/04-flex-information/README.md
  - flex/05-flex-modal/README.md
  - flex/06-flex-layout/README.md
  - flex/07-flex-layout-2/README.md
  - foundations/01-css-methods/README.md
  - foundations/02-class-id-selectors/README.md
  - foundations/03-grouping-selectors/README.md
  - foundations/04-chaining-selectors/README.md
  - foundations/05-descendant-combinator/README.md
  - foundations/06-cascade-fix/README.md
  - grid/01-grid-layout-1/README.md
  - grid/02-grid-layout-2/README.md
  - grid/03-grid-layout-3/README.md
  - margin-and-padding/01-margin-and-padding-1/README.md
  - margin-and-padding/02-margin-and-padding-2/README.md
